name: Flash Forge Homey App

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc

      - name: Run tests
        run: npm test

      - name: Install Homey CLI
        run: npm install -g homey typescript 

      - name: Validate Homey App
        run: homey app validate --level publish

      - name: Get last commit message
        id: last_commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Add new patch version with last commit message as changelog
      - name: Add new patch version with last commit message as changelog
          id: update_app_version
          run: |
            version=$(npx homey app version patch --changelog "${{ steps.last_commit.outputs.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            echo "version=$version" >> $GITHUB_OUTPUT

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update Homey App Version to v${{ steps.update_app_version.outputs.version }}"
          git tag "v${{ steps.update_app_version.outputs.version }}"

          git push https://x-access-token:${{ secrets.PAT_PUSH }}@github.com/arnovr/homey-flashforge.git HEAD --tags
          gh release create "v${{ steps.update_app_version.outputs.version }}" -t "v${{ steps.update_app_version.outputs.version }}" --notes "" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.PAT_PUSH }}


      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
