name: Flash Forge Homey App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to add (e.g. 1.0.3)'
        required: true
      changelog:
        description: 'Changelog for the new version'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust if needed

      - name: Install Homey CLI
        run: npm install -g homey

      - name: Validate Homey App
        run: homey app validate --level publish

      - name: Add new version
        run: |
          npx homey app version "${{ github.event.inputs.version }}" --changelog "${{ github.event.inputs.changelog }}"

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add app.json .homeycompose/app.json .homeychangelog.json
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push
